# Available tags:
# ${TIMESTAMP}, ${VICTIM}, ${KILLER}

# ${DATE} format examples:
# https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/SimpleDateFormat.html

# Locale for parsing date format (options defined in java.util.Locale)
locale: 'us'

# Configure for any EntityType (eg: skeleton, player, default)
lore-format:
  default: '${yyyy-MM-dd}'
  player: >-
    Killed by ${KILLER}
    ${yyyy-MM-dd}
